[package]
name = "rust_bq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcp-bigquery-client = "0.12.2"
serde_json = "^1.0.59"
tokio = {version = "1.17", features = ["full"]}

